version: "3"

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile-dev
        expose:
            - 4000
        environment:
            - MONGO_URI=mongodb://db:27017/db
            - PORT=4000
            - JWT_SECRET=secretsecret
            - JWT_EXPIRY=30d
            - DEBUG=worker:*
            - MORGAN=combined
            - NODE_ENV=development
        ports: 
            - 4000:4000
        volumes:
            - ./server/src:/app/server/src
        command: nodemon -L src/server.js --exec babel-node
        links:
            - db
        restart: always
    
    client:
        build:
            context: ./client
            dockerfile: Dockerfile-dev
        environment:
            - REACT_APP_PORT=3000
            - CHOKIDAR_USEPOLLING=true
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./client/src:/app/client/src
            - ./client/public:/app/client/public
        links:
            - server
        command: npm run start
        restart: always

    db:
        image: mongo
        ports:
            - 27017:27017
        restart: always
