FROM node

RUN npm install -g nodemon @babel/core @babel/cli @babel/preset-env @babel/node
# RUN npm install -g nodemon @babel/node


RUN mkdir -p /app/server
WORKDIR /app/server

COPY package*.json /app/server/

RUN npm install

COPY . /app/server

CMD ["nodemon", "src/server.js"]